### PR TITLE
feat(react): Manual mode for button

### PR DESCRIPTION
**Pull request by Mr0Bread**

### CODE REVIEW

**Comment by Mr0Bread** [comment]
@juliusmarminge I've raised that concern in our discord channel actually ;D

My idea was to introduce the "Clear" button. We could display it under the button instead of allowed content label

**Comment by juliusmarminge** [comment]
> My idea was to introduce the "Clear" button. We could display it under the button instead of allowed content label

Sounds good to me!

**Review by markflorkowski — APPROVED** [review]

**Comment by juliusmarminge** [comment]
Something's broken here. After clicking reset, I can't add new files?

CleanShot 2023-10-05 at 10 33 58

**Comment by Mr0Bread** [comment]
@juliusmarminge Fixed the issue

**Review by juliusmarminge — APPROVED** [review]

**Pull request merged**
