### PR TITLE
feat: React Native Support

### PR DESCRIPTION
**Pull request by Yash-Singh1**
This is an initial prototype of what react native support would look like.

TODO:
- [x] Fix vercel deployments
- [x] Add theming
- [x] Document props

### CODE REVIEW

**Comment by Yash-Singh1** [comment]
Not sure why the Vercel deployments are failing...

**Comment by markflorkowski** [comment]
> Not sure why the Vercel deployments are failing...

Not sure either, merged main just to be sure it wasn't something that we had already resolved. 

Error log doesn't make much sense: 
image


As a side note, I don't think that the full turborepo example should be in this repository. Potentially we are considering moving all of the samples out into template repos (similar to what Clerk does), but at the very least, RN is a weird enough/large enough example that I would prefer it not be in the main development repository.

**Comment by Yash-Singh1** [comment]
> As a side note, I don't think that the full turborepo example should be in this repository. Potentially we are considering moving all of the samples out into template repos (similar to what Clerk does), but at the very least, RN is a weird enough/large enough example that I would prefer it not be in the main development repository.

Sure, I'll move the `create-t3-turbo` example into a separate repository for now.

**Comment by Yash-Singh1** [comment]
<https://github.com/Yash-Singh1/uploadthing-ct3-turbo>. It won't work for now because the `@uploadthing/react-native` package isn't published yet, but the temporary fix would be to use `file:` in the `package.json`s and build the packages locally.

**Comment by t3dotgg** [comment]
80% sure I fixed the nextra build issue - mind merging main? To handle the pnpm lock conflict, just kill the lockfile and re-run pnpm install

**Comment by Yash-Singh1** [comment]
> 80% sure I fixed the nextra build issue - mind merging main? To handle the pnpm lock conflict, just kill the lockfile and re-run pnpm install

Just realized `pnpm` automatically handles merge conflicts in lockfiles: https://pnpm.io/git.

**Comment by Yash-Singh1** [comment]
@t3dotgg @markflorkowski I can finish up this PR once you think we're ready for React Native support.

**Comment by markflorkowski** [comment]
@Yash-Singh1 Sorry for the continued delays on this. We really want to make sure that the official recommendations that we make regarding RN are as good as possible and fit into the way that RN devs are used to working. 

I really appreciate your effort on this PR, and prompting us to think about this so we can bring the best experience to users of uploadthing.

**Comment by markflorkowski** [comment]
Did not mean to close. Sorry about that.

**Comment by t3dotgg** [comment]
Would love to get this in on the new community branch before I fork it into a repo

**Comment by rarepepi** [comment]
> Would love to get this in on the new community branch before I fork it into a repo

Is it in the community branch, I cant seem to find it? Thanks!

**Comment by k2on** [comment]
Any update on this?

**Comment by k2on** [comment]
https://github.com/Yash-Singh1/uploadthing-rn

Imma look at this

**Comment by k2on** [comment]
Once i started trying to apply patches you lost me haha.

RN can not find uploadthing/server or client module after patches get applied 🤷 

No idea what im doing

**Comment by Yash-Singh1** [comment]
I am working on a recreate of this PR, so I will close this one for now.

**Pull request closed without merging**
