### PR TITLE
fix(bug): declaration support broken

### PR DESCRIPTION
**Pull request by juliusmarminge**
Similar to #192

### CODE REVIEW

**Review by markflorkowski — APPROVED** [review]

**Comment by juliusmarminge** [comment]
I do wonder why CI is passing, build is failing locally.

(I haven't attempted on fixing it yet, just threw the PR up to show how to repro the build error for @GentikSolm)

**Comment by GentikSolm** [comment]
Hm, this is still working for me.
image

**Comment by juliusmarminge** [comment]
> Hm, this is still working for me.
> 
> image
> 
> 

So you not see errors in your editor? utils/uploadthing file on the `useUploadthing` hook?

**Comment by GentikSolm** [comment]
Ahh no i see it now. That is weird that it passes build and linting steps fine

**Comment by GentikSolm** [comment]
I have this nailed down to `UploadThingError`'s type not being able to be decoupled from its actual impl, so the type cant be inferred without reference to that folder.

**Comment by GentikSolm** [comment]
Tried throwing a bunch of stuff at the wall but nothing stuck. I can confirm that it is for sure `UploadThingError` though. For some reason its not able to pull the typedef out. Open to suggestions.

**Comment by juliusmarminge** [comment]
I wonder if it might not be best to nuke the shared pacakge all together, we can share stuff from the `uploadthing` package anyways

**Comment by GentikSolm** [comment]
that makes sense to me. I can take a stab at that refactor if thats the direction we want to go

**Comment by juliusmarminge** [comment]
Wut do you think @markflorkowski ? Should we just share code from the `uploadthing` pacakge?

**Comment by markflorkowski** [comment]
That seems reasonable enough to me. I did like the separation, but it isn't worth the headache.

**Comment by GentikSolm** [comment]
Making a new branch for this since i dont have write perms

**Comment by GentikSolm** [comment]
Resolved by #272

**Comment by markflorkowski** [comment]
Superseded by #272

**Pull request closed without merging**
