### PR TITLE
fix: exports of shared and mime-types

### PR DESCRIPTION
**Pull request by Mr0Bread**
Addresses #275 

Faced the same issue while working on ExpressJS adapter and example for it

### CODE REVIEW

**Review by markflorkowski — APPROVED** [review]
cc @t3dotgg

**Comment by juliusmarminge** [comment]
Why should these have `cjs` outputs when the main package doesn't?

https://github.com/pingdotgg/uploadthing/blob/9b1e2b722f5a80d5bb6205491e753998e4420d6b/packages/config/tsup/index.js#L7

https://github.com/pingdotgg/uploadthing/blob/9b1e2b722f5a80d5bb6205491e753998e4420d6b/packages/uploadthing/tsup.config.ts#L6-L16

**Comment by Mr0Bread** [comment]
Honestly, not sure why that error happens. Probably something to do with the resolution algorithm

**Comment by juliusmarminge** [comment]
I added the cjs export to the root config. Doesn't hurt to have it everywhere?

**Comment by Mr0Bread** [comment]
> I added the cjs export to the root config. Doesn't hurt to have it everywhere?

Seems reasonable

**Review by juliusmarminge — APPROVED** [review]

**Pull request merged**
