### PR TITLE
fix: page dir's req body needs to be parsed

### PR DESCRIPTION
**Pull request by miguelvelasquezdev**
pages dir is not working now, it needs to be parsed.

I hope this commit be helpful

### CODE REVIEW

**Comment by markflorkowski** [comment]
I just pulled the current `main` and tried the pagedir example and it seems to be working for me. Can you provide some more information about what was not working for you?

**Comment by miguelvelasquezdev** [comment]
are you sure?
I get this errors trying with page dir:
Screenshot 2023-05-27 at 3 31 56 PM
Screenshot 2023-05-27 at 3 31 43 PM

**Comment by markflorkowski** [comment]
Yeah, just deleted `node_modules` and `.next` as well to be sure it wasn't just something being cached

**Comment by miguelvelasquezdev** [comment]
do you have this changes in your code? https://github.com/pingdotgg/uploadthing/blob/16157de54198d0838007efb4f6a37a4cd8720bab/packages/uploadthing/src/internal/handler.ts#L188
https://github.com/pingdotgg/uploadthing/blob/16157de54198d0838007efb4f6a37a4cd8720bab/packages/uploadthing/src/next/core/page.ts#L41

If you see the new code doesn’t have JSON.parse, alike the previous code that had JSON.parse
https://github.com/pingdotgg/uploadthing/commit/845ada2ed504a1842ab203f4f5bc343a665cd875#diff-9cb45f5c348aa23d75574803fb7b59cecfeaf242247187e9a563148331fb9f4b

**Comment by markflorkowski** [comment]
Yep. I have both of those changes. I am using whatever is in main right now. 
image
image

**Comment by markflorkowski** [comment]
`req.json()` should be returning the body as json, no need to `JSON.parse()`

**Comment by markflorkowski** [comment]
Oh I see now what you are referring to. I am not sure why it is working totally fine for me

**Comment by markflorkowski** [comment]
cc @juliusmarminge

**Comment by juliusmarminge** [comment]
Ah whoopsies - my bad. Yea that should be JSON.parse'd.

**Review by juliusmarminge — APPROVED** [review]
Haven't tested but this should be json parsed indeed

**Comment by juliusmarminge** [comment]
Tested both before and after and this works! thanks for noticing.

**Comment by juliusmarminge** [comment]
oh whoopsies this was targetting the wrogn branch

**Pull request merged**
