### PR TITLE
showcase: show usage for cropping before uploading

### PR DESCRIPTION
**Pull request by juliusmarminge**
We don't have any example of usage with the hook. I thought this could be useful 🤷🏼 

https://github.com/pingdotgg/uploadthing/assets/51714798/47e0cca5-9ea9-4662-9ea8-5f60b0535af5

### CODE REVIEW

**Comment by markflorkowski** [comment]
We are considering moving examples out of this repo into a separate one, and using the current `examples` in the repo for testing purposes only. 

cc @t3dotgg on how soon we might want to do that

**Comment by juliusmarminge** [comment]
> We are considering moving examples out of this repo into a separate one, and using the current `examples` in the repo for testing purposes only. 
> 
> 
> 
> cc @t3dotgg on how soon we might want to do that

May I ask why? Examples are a great way to make sure you arent breaking types etc

**Comment by markflorkowski** [comment]
> > We are considering moving examples out of this repo into a separate one, and using the current `examples` in the repo for testing purposes only.
> > cc @t3dotgg on how soon we might want to do that
> 
> May I ask why? Examples are a great way to make sure you arent breaking types etc

It was mostly due to wanting more/better examples for users, but not wanting to continue cluttering this repo. We're not completely tied to doing it though, still early thoughts on the matter.

**Comment by juliusmarminge** [comment]
> It was mostly due to wanting more/better examples for users, but not wanting to continue cluttering this repo. We're not completely tied to doing it though, still early thoughts on the matter.

The E2E examples saves tRPC almost daily despite having over 90% test coverage 😅

**Review by t3dotgg — APPROVED** [review]
this is dope

**Pull request merged**
