### PR TITLE
feat: added onDrop prop for UploadDropzone component

### LINKED ISSUE #805: feat: Showing image preview of selected file before uploading
### Describe the feature you'd like to request

Currently, I am using `UploadDropzone` to handle the whole image upload flow. I can show a preview of the image by using the generated image URL. But if I want to show an image preview or do something with the selected file before even clicking on the upload button, there is no way I can access the selected file.

### Describe the solution you'd like to see

There should be an option in the [configuration](https://docs.uploadthing.com/api-reference/react#configuration-1) like `onFileSelect`, where I can pass a callback function to get access to the selected file.

```
<UploadDropzone
      onFileSelect={(selectedFile)=>{
        // here i can access the selected file
      }}
    />
```

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

### PR DESCRIPTION
**Pull request by growupanand**
Added a prop `onDrop` for the `<UploadDropzone />` component. Whenever the user selects or drops the file it will call the passed `onDrop` callback function.

Closes #805

### CODE REVIEW

**Review by juliusmarminge — CHANGES_REQUESTED** [review]
Thanks! Looks good.

Can you add a changeset and update docs too please

**Comment by growupanand** [comment]
I have updated docs and added changeset.

**Review by juliusmarminge — APPROVED** [review]

**Review by markflorkowski — APPROVED** [review]

**Comment by growupanand** [comment]
can you please merge this PR?

**Comment by juliusmarminge** [comment]
I am currently fixing our CI.

Seems like something broke in Node 20.13 which the runners seems to use since last night.

Will merge once everything's green 👍🏼

**Comment by growupanand** [comment]
Hey @juliusmarminge ,

In my [project](https://github.com/growupanand/ConvoForm), I am trying to publish a internal package of turborepo.
I am able to bundle it successfully and [published](https://www.npmjs.com/package/@convoform/react) it.
But when I am trying to use it in another react app, I am facing below error. Can you please help me with that whenever you got some time?

```
╰─$ npm install @convoform/react                                                                                                                                                                            130 ↵
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
```


Message here since I was not able to contact you on LinkedIn or Twitter 😅


https://github.com/growupanand/ConvoForm/commits/231-publish-react-hook-as-npm-package/

**Comment by juliusmarminge** [comment]
> Hey @juliusmarminge ,
> 
> In my [project](https://github.com/growupanand/ConvoForm), I am trying to publish a internal package of turborepo. I am able to bundle it successfully and [published](https://www.npmjs.com/package/@convoform/react) it. But when I am trying to use it in another react app, I am facing below error. Can you please help me with that whenever you got some time?
> 
> ```
> ╰─$ npm install @convoform/react                                                                                                                                                                            130 ↵
> npm ERR! code EUNSUPPORTEDPROTOCOL
> npm ERR! Unsupported URL Type "workspace:": workspace:*
> ```
> 
> Message here since I was not able to contact you on LinkedIn or Twitter 😅
> 
> https://github.com/growupanand/ConvoForm/commits/231-publish-react-hook-as-npm-package/

You cannot use `workspace:*` in published packages since the consumer won't have that workspace reference.

If you publish with pnpm it should replace the `workspace:*` with the proper version for you, but if you use npm you'll need to do it yourself. Hope that helps!

**Comment by growupanand** [comment]
> > Hey @juliusmarminge ,
> > In my [project](https://github.com/growupanand/ConvoForm), I am trying to publish a internal package of turborepo. I am able to bundle it successfully and [published](https://www.npmjs.com/package/@convoform/react) it. But when I am trying to use it in another react app, I am facing below error. Can you please help me with that whenever you got some time?
> > ```
> > ╰─$ npm install @convoform/react                                                                                                                                                                            130 ↵
> > npm ERR! code EUNSUPPORTEDPROTOCOL
> > npm ERR! Unsupported URL Type "workspace:": workspace:*
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Message here since I was not able to contact you on LinkedIn or Twitter 😅
> > https://github.com/growupanand/ConvoForm/commits/231-publish-react-hook-as-npm-package/
> 
> You cannot use `workspace:*` in published packages since the consumer won't have that workspace reference.
> 
> If you publish with pnpm it should replace the `workspace:*` with the proper version for you, but if you use npm you'll need to do it yourself.
> 
> If you don't wish to also publish the dependency, you'll have to bundle it into the `@convoform/react` dist
> 
> Hope that helps!



> > Hey @juliusmarminge ,
> > In my [project](https://github.com/growupanand/ConvoForm), I am trying to publish a internal package of turborepo. I am able to bundle it successfully and [published](https://www.npmjs.com/package/@convoform/react) it. But when I am trying to use it in another react app, I am facing below error. Can you please help me with that whenever you got some time?
> > ```
> > ╰─$ npm install @convoform/react                                                                                                                                                                            130 ↵
> > npm ERR! code EUNSUPPORTEDPROTOCOL
> > npm ERR! Unsupported URL Type "workspace:": workspace:*
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Message here since I was not able to contact you on LinkedIn or Twitter 😅
> > https://github.com/growupanand/ConvoForm/commits/231-publish-react-hook-as-npm-package/
> 
> You cannot use `workspace:*` in published packages since the consumer won't have that workspace reference.
> 
> If you publish with pnpm it should replace the `workspace:*` with the proper version for you, but if you use npm you'll need to do it yourself.
> 
> If you don't wish to also publish the dependency, you'll have to bundle it into the `@convoform/react` dist
> 
> Hope that helps!



> > Hey @juliusmarminge ,
> > In my [project](https://github.com/growupanand/ConvoForm), I am trying to publish a internal package of turborepo. I am able to bundle it successfully and [published](https://www.npmjs.com/package/@convoform/react) it. But when I am trying to use it in another react app, I am facing below error. Can you please help me with that whenever you got some time?
> > ```
> > ╰─$ npm install @convoform/react                                                                                                                                                                            130 ↵
> > npm ERR! code EUNSUPPORTEDPROTOCOL
> > npm ERR! Unsupported URL Type "workspace:": workspace:*
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Message here since I was not able to contact you on LinkedIn or Twitter 😅
> > https://github.com/growupanand/ConvoForm/commits/231-publish-react-hook-as-npm-package/
> 
> You cannot use `workspace:*` in published packages since the consumer won't have that workspace reference.
> 
> If you publish with pnpm it should replace the `workspace:*` with the proper version for you, but if you use npm you'll need to do it yourself.
> 
> If you don't wish to also publish the dependency, you'll have to bundle it into the `@convoform/react` dist
> 
> Hope that helps!

Thanks for the quick reply, I didn't know about that PNPM could insert the dependency version.

I have just tried to bundle it in the dist folder. I was able to publish it and then installed it in another React app successfully. But I am not able to use it and getting below error.

```
Unhandled Runtime Error
Error: Cannot find module 'fs'

Call Stack
webpackEmptyContext
file:///home/growupanand/Development/repos/ConvoForm/apps/web/.next/static/chunks/app/(protectedPage)/forms/%5BformId%5D/page.js (18:10)
__require
../node_modules/.pnpm/engine.io-client@6.5.3/node_modules/engine.io-client/build/cjs/contrib/yeast.js (46:9)
__require2
(app-pages-browser)/../../packages/react/dist/index.js
require_XMLHttpRequest
../node_modules/.pnpm/engine.io-client@6.5.3/node_modules/engine.io-client/build/cjs/transports/xmlhttprequest.js (15:21)
__require2
(app-pages-browser)/../../packages/react/dist/index.js
require_xmlhttprequest
../node_modules/.pnpm/engine.io-client@6.5.3/node_modules/engine.io-client/build/cjs/transports/xmlhttprequest.js (109:5)
__require2
(app-pages-browser)/../../packages/react/dist/index.js
require_polling
../node_modules/.pnpm/engine.io-client@6.5.3/node_modules/engine.io-client/build/cjs/transports/webtransport.js (58:26)
__require2
(app-pages-browser)/../../packages/react/dist/index.js
require_transports
../node_modules/.pnpm/engine.io-client@6.5.3/node_modules/engine.io-client/build/cjs/contrib/parseuri.js (42:13)
```


Would you kindly assist me with this as well? I would really appreciate it. And I have created an i[ssue here](https://github.com/growupanand/ConvoForm/issues/244) for the discussion.

**Comment by growupanand** [comment]
> > > Hey @juliusmarminge ,
> > > In my [project](https://github.com/growupanand/ConvoForm), I am trying to publish a internal package of turborepo. I am able to bundle it successfully and [published](https://www.npmjs.com/package/@convoform/react) it. But when I am trying to use it in another react app, I am facing below error. Can you please help me with that whenever you got some time?
> > > ```
> > > ╰─$ npm install @convoform/react                                                                                                                                                                            130 ↵
> > > npm ERR! code EUNSUPPORTEDPROTOCOL
> > > npm ERR! Unsupported URL Type "workspace:": workspace:*
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Message here since I was not able to contact you on LinkedIn or Twitter 😅
> > > https://github.com/growupanand/ConvoForm/commits/231-publish-react-hook-as-npm-package/
> > 
> > 
> > You cannot use `workspace:*` in published packages since the consumer won't have that workspace reference.
> > If you publish with pnpm it should replace the `workspace:*` with the proper version for you, but if you use npm you'll need to do it yourself.
> > If you don't wish to also publish the dependency, you'll have to bundle it into the `@convoform/react` dist
> > Hope that helps!
> 
> > > Hey @juliusmarminge ,
> > > In my [project](https://github.com/growupanand/ConvoForm), I am trying to publish a internal package of turborepo. I am able to bundle it successfully and [published](https://www.npmjs.com/package/@convoform/react) it. But when I am trying to use it in another react app, I am facing below error. Can you please help me with that whenever you got some time?
> > > ```
> > > ╰─$ npm install @convoform/react                                                                                                                                                                            130 ↵
> > > npm ERR! code EUNSUPPORTEDPROTOCOL
> > > npm ERR! Unsupported URL Type "workspace:": workspace:*
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Message here since I was not able to contact you on LinkedIn or Twitter 😅
> > > https://github.com/growupanand/ConvoForm/commits/231-publish-react-hook-as-npm-package/
> > 
> > 
> > You cannot use `workspace:*` in published packages since the consumer won't have that workspace reference.
> > If you publish with pnpm it should replace the `workspace:*` with the proper version for you, but if you use npm you'll need to do it yourself.
> > If you don't wish to also publish the dependency, you'll have to bundle it into the `@convoform/react` dist
> > Hope that helps!
> 
> > > Hey @juliusmarminge ,
> > > In my [project](https://github.com/growupanand/ConvoForm), I am trying to publish a internal package of turborepo. I am able to bundle it successfully and [published](https://www.npmjs.com/package/@convoform/react) it. But when I am trying to use it in another react app, I am facing below error. Can you please help me with that whenever you got some time?
> > > ```
> > > ╰─$ npm install @convoform/react                                                                                                                                                                            130 ↵
> > > npm ERR! code EUNSUPPORTEDPROTOCOL
> > > npm ERR! Unsupported URL Type "workspace:": workspace:*
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Message here since I was not able to contact you on LinkedIn or Twitter 😅
> > > https://github.com/growupanand/ConvoForm/commits/231-publish-react-hook-as-npm-package/
> > 
> > 
> > You cannot use `workspace:*` in published packages since the consumer won't have that workspace reference.
> > If you publish with pnpm it should replace the `workspace:*` with the proper version for you, but if you use npm you'll need to do it yourself.
> > If you don't wish to also publish the dependency, you'll have to bundle it into the `@convoform/react` dist
> > Hope that helps!
> 
> Thanks for the quick reply, I didn't know about that PNPM could insert the dependency version.
> 
> I have just tried to bundle it in the dist folder. I was able to publish it and then installed it in another React app successfully. But I am not able to use it and getting below error.
> 
> ```
> Unhandled Runtime Error
> Error: Cannot find module 'fs'
> 
> Call Stack
> webpackEmptyContext
> file:///home/growupanand/Development/repos/ConvoForm/apps/web/.next/static/chunks/app/(protectedPage)/forms/%5BformId%5D/page.js (18:10)
> __require
> ../node_modules/.pnpm/engine.io-client@6.5.3/node_modules/engine.io-client/build/cjs/contrib/yeast.js (46:9)
> __require2
> (app-pages-browser)/../../packages/react/dist/index.js
> require_XMLHttpRequest
> ../node_modules/.pnpm/engine.io-client@6.5.3/node_modules/engine.io-client/build/cjs/transports/xmlhttprequest.js (15:21)
> __require2
> (app-pages-browser)/../../packages/react/dist/index.js
> require_xmlhttprequest
> ../node_modules/.pnpm/engine.io-client@6.5.3/node_modules/engine.io-client/build/cjs/transports/xmlhttprequest.js (109:5)
> __require2
> (app-pages-browser)/../../packages/react/dist/index.js
> require_polling
> ../node_modules/.pnpm/engine.io-client@6.5.3/node_modules/engine.io-client/build/cjs/transports/webtransport.js (58:26)
> __require2
> (app-pages-browser)/../../packages/react/dist/index.js
> require_transports
> ../node_modules/.pnpm/engine.io-client@6.5.3/node_modules/engine.io-client/build/cjs/contrib/parseuri.js (42:13)
> ```
> 
> Would you kindly assist me with this as well? I would really appreciate it. And I have created an i[ssue here](https://github.com/growupanand/ConvoForm/issues/244) for the discussion.

It is fixed.

**Pull request merged**
