### PR TITLE
 enable plugin in your ESLint

### PR DESCRIPTION
**Pull request by Abhijit20112003**

### CODE REVIEW

**Review by Abhijit20112003 — COMMENTED** [review]
Configuration is a recommended TypeScript for type-checking.

**Comment by markflorkowski** [comment]
Enabling the plugin is nice, but you will need to actually fix the code that is failing lint before this is mergable.

**Comment by nickmccurdy** [comment]
The config also appears to be broken in CI

**Comment by Abhijit20112003** [comment]
@markflorkowski the lint issues have been resolved!

**Comment by t3dotgg** [comment]
You have continued to not actually run the code locally to make sure linting is working, @Abhijit20112003. Tested on my machine and you didn't even set the parser, much less fix any code that the lint rule would flag.

Closing.

image

**Pull request closed without merging**
