### PR TITLE
chore: Update solidstart example

### PR DESCRIPTION
**Pull request by juraj98**
When working on example for `tanstack/start` I ran into CI lint issue because of different versions of `vinxi` for `SolidStart` and `tanstack/start`. I decided to update the solidstart example first. Full list of changes:

- Updated dependencies to the newest version with appropriate code changes.
- ~~Removed tailwind and imported `@uploadthing/solid/styles.css` instead.~~
- Removed unimportant meta tags
- Changed few `console.log`s and `alert`s in index route to be consistent. 

I'll update solid start getting started docs next and link the PR here. 

@juliusmarminge, this might conflict with #980.

## Summary by CodeRabbit

- **New Features**
	- Introduced a new Tailwind CSS configuration for improved styling.
	- Added `autoprefixer` for better CSS compatibility.

- **Bug Fixes**
	- Updated several dependencies, including `solid-js`, for enhanced performance and stability.

- **Documentation**
	- Updated project configuration files to reflect new module syntax and engine requirements.

- **Chores**
	- Removed outdated components and imports from the main application file.

### CODE REVIEW

**Comment by juliusmarminge** [comment]
> @juliusmarminge, this might conflict with #980.

Perfectly fine that update was also a side effect of me realizing the example wasn't working when I was working on something else 😊

If you don't mind adding tailwind back in though, just hard code the path like I did in my PR. I'll look into issue #975 later.

**Comment by juraj98** [comment]
@juliusmarminge, I removed tailwind because it doesn't fit the "minimal" part of the example, not because of #975. `minimal-expo` is the only one "minimal" that has tailwind. `minimal-appdir`, `minimal-astro-react`, `minimal-nuxt`, `minimal-pagedir`, and `minimal-sveltekit` all don't have tailwind. Can add it back though.

**Comment by juliusmarminge** [comment]
ah, i see your point...

i just love having tailwind installde when needing to test theming overrides. we have many react examples so makes sense for those not to have it but for the one solid example it's nice to have i tihnk

**Comment by juraj98** [comment]
Got you. I'll add tailwind back as soon as I figure out this **** common range dependency lint issue 😂

**Comment by juliusmarminge** [comment]
pnpm manypkg fix is your friend for that

**Review by juliusmarminge — APPROVED** [review]

**Pull request merged**
