### PR TITLE
[DOCS] Add a button to take the user to the dashboard 

### PR DESCRIPTION
**Pull request by perkinsjr**
Adds a button to the dashboard so it can be accessed anywhere. 

- Added a css hack to style a div. 
- Use the Nextra Project to link and open in new tab.

### CODE REVIEW

**Comment by markflorkowski** [comment]
Looks like build is mad about key order:

image

**Comment by markflorkowski** [comment]
Ah I did not realize this would conflict with #63 😓. 

Would you mind porting this over to use [_meta.json](https://nextra.site/docs/docs-theme/page-configuration#links)?

**Comment by perkinsjr** [comment]
Sure <3

**Comment by perkinsjr** [comment]
Hey @markflorkowski 

Which do you want? Both are possible, the one on the left uses the pages so it ends up in the menu on mobile but can't be styled. 

The other one is using the extraContent options. Either way is fine with me but can push whatever. 

image

**Pull request closed without merging**
