### PR TITLE
fix(docs): prevent escape from throwing error when no toast is open

### PR DESCRIPTION
**Pull request by benox3**
Pressing escape on api reference page causes an error due to some weirdness with `vueaury` + `vue-sonner`. We just patch the package to add an additional type check for `vue-sonner` for whether the contains function is available.

Resolves:
```Uncaught TypeError: r.contains is not a function``` on openapi spec page

### CODE REVIEW

**Comment by juliusmarminge** [comment]
https://docs.uploadthing.com/api-reference/openapi-spec tried pressing escape in a bunch of ways but didn't get any error. Can you record the issue you're seeing?

**Comment by markflorkowski** [comment]
> https://docs.uploadthing.com/api-reference/openapi-spec tried pressing escape in a bunch of ways but didn't get any error. Can you record the issue you're seeing?


https://github.com/pingdotgg/uploadthing/assets/11494384/740eef77-746f-498a-bf55-a5b0b0a4863d

**Comment by benox3** [comment]
Thanks @markflorkowski -- that's the one. 

Seems like the preview still has the issue. I'm wondering if the vercel deploy is using cache, otherwise it could be something off with the patching which was kind of finicky to implement with bun.

**Comment by markflorkowski** [comment]
> Seems like the preview still has the issue. I'm wondering if the vercel deploy is using cache, otherwise it could be something off with the patching which was kind of finicky to implement with bun.

Being on the docs site, I would not be surprised if this were the case. We have had a ton of build cache issues with Nextra :/

**Pull request merged**
