### PR TITLE
add : how to allow multi-file upload

### PR DESCRIPTION
**Pull request by kj-1809**

### CODE REVIEW

**Review by markflorkowski — CHANGES_REQUESTED** [review]
Please add this to all docs examples (pagedir/appdir/solid), then I think it should be good to merge 👍

**Comment by t3dotgg** [comment]
@markflorkowski I'd prefer to not clog up the examples with this and put it in the api docs instead, can be convinced either way tho

**Comment by markflorkowski** [comment]
Yeah, this would be good as part of the generic api docs

**Comment by t3dotgg** [comment]
Closing in favor of me working on better api docs

**Pull request closed without merging**
